apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: openvpns.ibm.com
spec:
  group: ibm.com
  names:
    kind: OpenVPN
    listKind: OpenVPNList
    plural: openvpns
    singular: openvpn
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
    - name: v1alpha1
      served: true
      storage: true